services:
  backend:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    volumes:
      - ./app:/app
    networks:
      - habit_net
    environment:
      - PYTHONDONTWRITEBYTECODE=1
  postgres:
    image: postgres:15
    container_name: postgres_habit_tracker
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: habitdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - habit_net

volumes:
  postgres_data:

networks:
  habit_net:
