### Get all habits
GET http://localhost/api/habits

### Create a new habit
POST http://localhost/api/habits
Content-Type: application/json

  {
    "name": "Tomar banho",
    "frequency": ["Su"]
  }


### Obter hábitos agendados para uma data específica
GET http://localhost/api/habits/scheduled
    ?date=2025-07-27
    ## ANO MES DIA

#### Delete a habit
DELETE http://localhost/api/habits/22



### DELETE ALL habits