### Get all habits
GET http://localhost:8000/habits

### Create a new habit
POST http://localhost:8000/habits
Content-Type: application/json

  {
    "name": "limpar",
    "frequency": ["Su"]
  }


### Obter hábitos agendados para uma data específica
GET http://localhost:8000/habits/scheduled
    ?date=2025-10-12
    ## ANO MES DIA

#### Delete a habit
DELETE http://localhost:8000/habits/3

